name: Release
on:
  workflow_dispatch: # manual release

jobs:
  npm:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        projects: [prismerge, nestjs-prisma, request-parser]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup NPM
        uses: ng-easy/npm-setup@v2

      - name: Run Prisma Generate
        run: npx prisma generate

      - name: Build Package
        run: npx nx run build ${{ matrix.project}}

      - name: Release Package
        run: npx nx run release ${{ matrix.project }}
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Release
      #   uses: mansagroup/nrwl-nx-action@v2.1.0
      #   with:
      #     targets: release
      #     all: 'false'
      #     projects: ${{ matrix.projects }}
      #   env:
      #     CI: true
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
